server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      tracking-modes: cookie

spring:
  profiles:
    include: oauth, db
  messages:
    basename: messages,errors

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

decorator:
  datasource:
    p6spy:
      enable-logging: true

#logging.level:
#  org.hibernate.SQL: debug

file:
  profile: /Users/hipo/Desktop/hipo/src/main/resources/static/profile_img/
